import type { VideoMimeType } from 'vidstack';

declare global {
	type User = {
		id: string;
		username: string;
		platform: Platform;
		avatar: number[];
	};

	type Feed = {
		twitch: LiveNow[] | null;
		youtube: FeedVideo[] | null;
	};

	type LiveNow = {
		username: string;
		startedAt: string;
	};

	type FeedVideo = {
		id: string;
		username: string;
		title: string;
		publishedAt: number;
		viewCount: string;
	};

	type WatchPageVideo = {
		id: string;
		channel: Channel;
		metadata: Metadata;
		chapters: Chapter[];
		subtitles: Subtitle[];
		videoFormats: Format[];
		audioFormats: Format[];
	};

	type Channel = {
		id: string;
		name: string;
		avatar: string;
	};

	type Metadata = {
		title: string;
		description: string;
		publishedDateTxt: string;
		viewCount: number;
	};

	type Chapter = {
		name: string;
		position: number;
	};

	type Subtitle = {
		url: string;
		lang: string;
		langName: string;
		autoGenerated: boolean;
	};

	type Format = {
		src: string;
		codec: string;
		type: VideoMimeType;
		height: number;
		width: number;
	};

	type ChatEvent = {
		event: 'message';
		data: ChatMessage;
	};

	type ChatMessage = {
		id: number;
		// Color
		c: string;
		// First message, not used
		f: boolean;
		// Name
		n: string;
		// Fragments that make up the message
		m: MessageFragment[];
	};

	type MessageFragment = {
		// Type, 0 = text, 1 = emote, 2 = url
		t: number;
		// Content
		c: string;
		// Emote
		e: Emote;
	};

	type Emote = {
		// Name
		n: string;
		// URL
		u: string;
		// Width
		w: number;
		// Height
		h: number;
	};
}

export {};
