name: "build"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libasound2-dev libappindicator3-dev librsvg2-dev patchelf nsis lld llvm

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~\AppData\Roaming\npm-cache
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install npm dependencies
        run: npm ci

      - name: Run frontend lint
        run: npm run lint && npm run check

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install cargo-xwin
        run: cargo install cargo-xwin

      - uses: Swatinem/rust-cache@v2

      - name: Run clippy
        working-directory: src-tauri
        run: cargo clippy

      - name: Build for Linux
        run: npm run tauri build

      - name: Build for Windows
        run: npm run tauri build -- --runner cargo-xwin --target x86_64-pc-windows-msvc

      - uses: actions/upload-artifact@v4
        with:
          path: src-tauri/target/release/bundle/
